### ISSUE TITLE
【AMS】广告分析-添加筛选框异常

### ISSUE THREAD

**Issue by xuelin-0** [cuckoo-science/bug#13]
描述：
添加筛选条件，点击“添加筛选条件”按钮，页面新增4个筛选框，点击第1个筛选框的“删除”按钮，4个筛选框同时被删除

步骤：
1.进入广告分析模块
2.点击“添加筛选条件”按钮
3.页面同时新增4个筛选框

实际结果：
![image](https://user-images.githubusercontent.com/42426410/44437305-2e276a00-a5ec-11e8-96be-344479e9f75c.png)

期望结果：
点击“添加筛选条件”按钮，应该新增1个筛选框

**Comment by liuqiyu** [comment]
添加缓存引起的BUG,昨晚已解决！
