### ISSUE TITLE
【AMS】广告分析-添加筛选条件输入相同数值时无法查询到正确结果

### ISSUE THREAD

**Issue by xuelin-0** [cuckoo-science/bug#6]
描述：筛选条件的数值框输入相同的数值，无法筛选到对应数据记录（该数据记录存在）

步骤：
1.进入广告分析模块-产品/建站url/广告系列/广告组页签
2.点击添加盈利cpa/止损cpa筛选条件
3.输入相同的数值（对应的该数据记录存在）
4.点击查询

实际结果：
![image](https://user-images.githubusercontent.com/42426410/44255659-666c2880-a239-11e8-92f3-69dd841c0bab.png)
![image](https://user-images.githubusercontent.com/42426410/44255671-6ff59080-a239-11e8-8e3f-8099163d749e.png)

期望结果：
筛选后显示对应筛选条件的正确结果

**Comment by xuelin-0** [comment]
测试通过

**Comment by liuqiyu** [comment]
已验收
